import React from 'react'
import { Col, Row } from 'react-bootstrap'
import TitleNewComponent from '../elements/titleNew/TitleNewComponent'
import NumberChecklist from '../elements/numberedChecklist/NumberChecklist'
import ImageComponent from '../elements/imageComponent/ImageComponent'
import styles from './ourServicesNew.module.css'
const AndroidTabComponent = () => {
    return (
        <div className={styles.full_box_3}>
            <Row>
                <Col md="4"><ImageComponent image={'/images/services/wenBg.jpg'} /></Col>
                <Col md="5">
                    <div className={styles.box_3}>
                        <TitleNewComponent sub_title={"Launch faster. Scale smarter"} main_title={"With Android App Development"} desc={"The following outlines our web-development process, which can be split into several sensible elements:"} />
                        <NumberChecklist
                            numbers={["01", "02", "03", "04", "05", "06"]}
                            points={["Technical analysis",
                                "Planning and Idea",
                                "Design and Copywriting",
                                "Front- & Back-End Coding",
                                "Quality Assurance",
                                "Testing and Launch"
                            ]} />
                        <h6>Package start from<b>$600</b></h6>
                    </div>
                </Col>


                <Col md="3">
                    <div className={styles.badge}>
                        <div className={styles.badgeRound}>
                            <h4><span>30+</span>Million</h4>
                        </div>
                        <p>Revenue generated by our partner and clients since 2005</p>
                        <a href="#">View Case Study</a>
                    </div>
                </Col>
            </Row>

        </div>
    )
}

export default AndroidTabComponent