import React from 'react'
import { Col, Row } from 'react-bootstrap'
import TitleNewComponent from '../elements/titleNew/TitleNewComponent'
import NumberChecklist from '../elements/numberedChecklist/NumberChecklist'
import ImageComponent from '../elements/imageComponent/ImageComponent'
import styles from './ourServicesNew.module.css'
const AndroidTabComponent = () => {
    return (
        <div className={styles.full_box_3}>
            <Row>
                <Col md="4"><ImageComponent image={'/images/services/wenBg.jpg'} /></Col>
                <Col md="5">
                    <div className={styles.box_3}>
                        <TitleNewComponent sub_title={"Launch faster. Scale smarter"} main_title={"RFID Workflow Automation Solution"} 
                        desc={"Streamline operations with our RFID-based workflow automation solution, enabling real-time tracking, improved accuracy, and efficient process management across your business."} />
                        <NumberChecklist
                            numbers={["01", "02", "03", "04", "05"]}
                            points={[
                                "RFID system design and architecture",
                                "Hardware selection and integration (RFID tags, readers, antennas)",
                                "Real-time asset and inventory tracking",
                                "Workflow mapping and automation",
                                "Integration with ERP/WMS/CRM systems",
                                

                            ]} />
                        <h6>Package start from<b>$600</b></h6>
                    </div>
                </Col>


                <Col md="3">
                <NumberChecklist
                            numbers={[ "06","07", "08", "09", "10"]}
                            points={[
                                "RFID software development and customization",
                                "Data capture and analytics dashboards",
                                "Access control and security solutions",
                                "RFID system testing and deployment",
                                "Staff training and technical support",

                            ]} />
                    <div className={styles.badge}>
                        <div className={styles.badgeRound}>
                            <h4><span>30+</span>Million</h4>
                        </div>
                        <p>Revenue generated by our partner and clients since 2005</p>
                        <a href="#">View Case Study</a>
                    </div>
                </Col>
            </Row>

        </div>
    )
}

export default AndroidTabComponent