import React from 'react'
import { Col, Row } from 'react-bootstrap'
import TitleNewComponent from '../elements/titleNew/TitleNewComponent'
import NumberChecklist from '../elements/numberedChecklist/NumberChecklist'
import ImageComponent from '../elements/imageComponent/ImageComponent'
import styles from './ourServicesNew.module.css'
const ErpTabComponent = () => {
    return (
        <div className={styles.full_box_3}>
            <Row>
                <Col md="4"><ImageComponent image={'/images/services/wenBg.jpg'} /></Col>
                <Col md="5">
                    <div className={styles.box_3}>
                        <TitleNewComponent sub_title={"Launch faster. Scale smarter"} main_title={"ERP & Interoperability Solution"} 
                        desc={"Integrate and optimize your enterprise systems with our ERP and interoperability solution, ensuring seamless data exchange, improved efficiency, and smarter decision-making across platforms."} />
                        <NumberChecklist
                            numbers={["01", "02", "03", "04", "05","06", "07"]}
                            points={[
                                "ERP system evaluation and implementation",
                                "Business process analysis and optimization",
                                "Integration of ERP with third-party applications",
                                "Data migration and cleansing",
                                "Custom module development",
                                "Real-time data synchronization across systems",
                                "API and middleware development",
                                
                                

                            ]} />
                        {/* <h6>Package start from<b>$600</b></h6> */}
                    </div>
                </Col>


                <Col md="3">
                <NumberChecklist
                            numbers={["08","09", "10", "11", "12","13"]}
                            points={[
                                "User training and documentation",
                                "System performance monitoring and optimization",
                                "Post-implementation support and maintenance",
                                "Multi-Cloud/ Hybrid ERP Integration",
                                "Change Management", 
                                "AI/ML Enhancements", 

                            ]} />
                    {/* <div className={styles.badge}>
                        <div className={styles.badgeRound}>
                            <h4><span>30+</span>Million</h4>
                        </div>
                        <p>Revenue generated by our partner and clients since 2005</p>
                        <a href="#">View Case Study</a>
                    </div> */}
                </Col>
            </Row>

        </div>
    )
}

export default ErpTabComponent