export const menuActionTypes = {
    SET_PRODUCT_TAB_KEY: 'SET_PRODUCT_TAB_KEY',
    SET_MENU_ITEM: 'SET_MENU_ITEM',
    SET_PRODUCT_ITEM: 'SET_PRODUCT_ITEM',
    SET_SUB_CAT: 'SET_SUB_CAT',
    SET_IS_LOADING: 'SET_IS_LOADING',

}